### ISSUE TITLE
Autobuild/deploy documentation

### ISSUE THREAD

**Issue by JosiahBull** [file-share-platform/ws-com-framework#2]
## Description
Add a gh action to automatically build & deploy gh documentation.

## Tasks/General Thoughts
- [x] Add gh action
- [x] setup auto-deploy to gh-page
- [x] add badge to readme
- [x] Link to docs in repo description
